@startuml casper
left to right direction
skinparam packageStyle rectangle
actor customer
actor clerk
rectangle checkout {
  (checkout) .> (payment) : include
(help) .> (checkout) : extends
(checkout) -- clerk
customer -- checkout
(checkout) .> (payment) : include
  
}
@enduml
